2020-07-04 20:59:55,278 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:08:28,333 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:09:25,245 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:09:29,887 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:09:37,763 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:18,372 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:22,875 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:32,542 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:37,007 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:43,452 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-04 21:11:54,658 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-09 20:36:26,789 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-12 18:23:04,091 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-12 18:52:46,750 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-12 18:53:13,204 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-12 19:02:04,655 INFO: Microblog startup [in /Users/alistairgillespie/Projects/compass/app/__init__.py:74]
2020-07-12 19:02:08,014 ERROR: Exception on / [GET] [in /Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alistairgillespie/Projects/compass/app/main/routes.py", line 38, in index
    posts = current_user.followed_posts().paginate(
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
2020-07-12 19:02:10,378 ERROR: Exception on /index [GET] [in /Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alistairgillespie/Projects/compass/app/main/routes.py", line 38, in index
    posts = current_user.followed_posts().paginate(
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
2020-07-12 19:02:11,106 ERROR: Exception on /index [GET] [in /Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alistairgillespie/Projects/compass/app/main/routes.py", line 38, in index
    posts = current_user.followed_posts().paginate(
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
2020-07-12 19:02:11,682 ERROR: Exception on /index [GET] [in /Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alistairgillespie/Projects/compass/app/main/routes.py", line 38, in index
    posts = current_user.followed_posts().paginate(
  File "/Users/alistairgillespie/Projects/compass/compass/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
